// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mebdmsjilkugdbrwfeqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lYmRtc2ppbGt1Z2RicndmZXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2Nzk2NjcsImV4cCI6MjA1ODI1NTY2N30.ALtVZOtiJZ9H9Lgwa60UESycl8c8mwJrQVxSVfs8j6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);